INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (16, 'Anurag', '{1,2,3,7}', CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (2, 'Bob', '{1,2,3}', CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (3, 'Vivek', '{1,7}', CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (4, 'Prasannaa', '{1,2,3,7}', CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (5, 'Mark', '{2,5,7}', CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (1, 'Sam', '{3,5,7}', CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (6, 'Ganesh', '{4,5,6}', CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (7, 'Josh', '{1,3}',  CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (8, 'Rita', '{1,2}', CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (9, 'Shraddha', '{4,5}', CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (10, 'Pradeep', '{1,2,6}',  CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (11, 'Mahesh', '{1}', CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (12, 'Alex', '{1,2,3}', CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (13, 'Torry', '{1,2}', CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (14, 'Ben', '{1}',  CURRENT_DATE);
INSERT INTO agent_rt("id","name", "skill_ids",  "created_date") VALUES (15, 'Ram', '{1,2,3}', CURRENT_DATE);

INSERT INTO skill_rt("id", "name") VALUES (1, 'Java');
INSERT INTO skill_rt("id", "name") VALUES (2, 'UI');
INSERT INTO skill_rt("id", "name") VALUES (3, 'Cache');
INSERT INTO skill_rt("id", "name") VALUES (4, 'Testing');
INSERT INTO skill_rt("id", "name") VALUES (5, 'Integration');
INSERT INTO skill_rt("id", "name") VALUES (6, 'DevOps');
INSERT INTO skill_rt("id", "name") VALUES (7, 'Python');
